pronia-store/store/pages/urls.py
from django.urls import path

from .views import *

app_name = 'pages'

urlpatterns = [
    path('error/404', NotFoundView.as_view(), name='404'),
    path('about/', AboutView.as_view(), name='about'),
    path('blog/', blog, name='blog'),
    path('blog/detail/', blog_detail, name='blog-detail'),
    path('faq/', FAQView.as_view(), name='faq'),
]

pronia-store/store/products/urls.py
from django.urls import path

from .views import *

app_name = 'products'

urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('category/<category_name>/', ProductListView.as_view(), name='categories'),
    path('page/<int:page>/', ProductListView.as_view(), name='paginator'),
    path('cart/', CartView.as_view(), name='cart'),
    path('compare/', CompareView.as_view(), name='compare'),
    path('product/sale/', products_sale, name='sale'),
    path('product/<product_name>/', product, name='product'),

    path('product/wishlist/add/<int:product_id>/', wishlist_add, name='wishlist_add'),
    path('product/wishlist/remove/<int:product_id>/', wishlist_remove, name='wishlist_remove'),
    path('cart/add/<int:product_id>/', basket_add, name='basket_add'),
    path('cart/minus/<int:basket_id>/', basket_minus, name='basket_minus'),
    path('cart/remove/<int:basket_id>/', basket_remove, name='basket_remove')
]

pronia-store/store/store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from store.pages.views import *
from store.products.views import *
from store.users.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('shop/', include('products.urls', namespace='shop')),
    path('pages/', include('pages.urls', namespace='pages')),
    path('user/', include('users.urls', namespace='user')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pronia-store/store/users/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, include

from .views import *

app_name = 'users'

urlpatterns = [
    path('cart/checkout/', CheckoutView.as_view(), name='checkout'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('verify/<str:email>/<uuid:code>/', EmailVerificationView.as_view(), name='email_verification'),
    path('register/', UserRegistrationView.as_view(), name='register'),
    path('logout/', logout, name='logout'),
    path('account/<int:pk>', login_required(UserProfileView.as_view()), name='account'),
    path('wishlist/', WishlistView.as_view(), name='wishlist'),
]

pronia-store/store/products/models.py
from django.db import models

from users.models import User


class Categories(models.Model):
    name = models.CharField(max_length=32)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return f'{self.name}'


class Color(models.Model):
    name = models.CharField(max_length=32)

    class Meta:
        verbose_name_plural = 'Color'

    def __str__(self):
        return f'{self.name}'


class Tag(models.Model):
    name = models.CharField(max_length=32)

    class Meta:
        verbose_name_plural = 'Tags'

    def __str__(self):
        return f'{self.name}'


class Products(models.Model):
    name = models.CharField(max_length=128)
    price = models.DecimalField(max_digits=6, decimal_places=1)
    description = models.TextField(blank=True, null=True)
    size = models.CharField(max_length=32)
    stock = models.BooleanField(default=False)
    image = models.ImageField(upload_to='products_images')
    main_index = models.BooleanField(default=False)
    bestseller_index = models.BooleanField(default=False)
    latest_index = models.BooleanField(default=False)
    created_data = models.DateField(auto_now_add=True)
    color = models.ForeignKey(Color, on_delete=models.CASCADE)
    category = models.ForeignKey(Categories, on_delete=models.CASCADE)
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'Products'

    def __str__(self):
        return f'Товар {self.name}'


class ShopImage(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products_images', blank=True)

    class Meta:
        verbose_name_plural = 'ShopImages'

    def __str__(self):
        return f'Картинка для {self.product.name}'


class Index(models.Model):
    title = models.CharField(max_length=256)
    description = models.TextField()
    dop_description = models.TextField(blank=True, null=True)
    client_index = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = 'Index'

    def __str__(self):
        return f'Заголовок {self.title}'


class IndexImage(models.Model):
    main_item = models.ForeignKey(Index, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='main_images', blank=True)

    class Meta:
        verbose_name_plural = 'IndexImages'

    def __str__(self):
        return 'Картинка для главной страницы'


class IndexBanner(models.Model):
    name = models.CharField(max_length=64)
    description = models.CharField(max_length=64)
    image = models.ImageField(upload_to='main_images')

    class Meta:
        verbose_name_plural = 'IndexBanner'

    def __str__(self):
        return 'Баннер для главной страницы'


class Achievements(models.Model):
    count = models.PositiveIntegerField()
    name = models.CharField(max_length=16)

    class Meta:
        verbose_name_plural = 'Achievements'

    def __str__(self):
        return f'{self.name} Под видео'


class BasketQuerySet(models.QuerySet):
    def total_sum(self):
        return sum(basket.sum() for basket in self)

    def total_quantity(self):
        return sum(basket.quantity for basket in self)


class Basket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=0)

    objects = BasketQuerySet.as_manager()

    def __str__(self):
        return f'Товар {self.product.name} для {self.user}'

    def sum(self):
        return self.product.price * self.quantity


class Wishlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Products, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'Wishlist'

    def __str__(self):
        return f'{self.product.name} для {self.user}'


class Compare(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Products, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'Compare'

    def __str__(self):
        return f'Сравнение для {self.user}'

pronia-store/store/products/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import HttpResponseRedirect, render
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.core.cache import cache

from .count import *
from .models import *


class IndexView(TemplateView):
    template_name = 'products/index.html'
    
    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data()
        context['titles'] = Index.objects.all()
        context['images'] = IndexImage.objects.filter(main_item=1)
        context['big_banner'] = IndexBanner.objects.last()
        context['banners'] = IndexBanner.objects.exclude(name='Indoore Plant')
        context['main_products'] = Products.objects.filter(main_index=True)
        context['bestseller_products'] = Products.objects.filter(main_index=True, bestseller_index=True)
        context['latest_products'] = Products.objects.filter(main_index=True, latest_index=True)
        context['achievements'] = Achievements.objects.all()

        return context


class CartView(TemplateView):
    template_name = 'products/cart.html'


class CompareView(TemplateView):
    template_name = 'products/compare.html'


class ProductListView(ListView):
    model = Products
    template_name = 'products/shop.html'
    paginate_by = 6
    
    def get_queryset(self):
        queryset = super(ProductListView, self).get_queryset()
        category_name = self.kwargs.get('category_name')
        return queryset.filter(category__name=category_name) if category_name else queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductListView, self).get_context_data()
        context['categories'] = Categories.objects.all()
        context['tags'] = Tag.objects.all()
        context['prod_all'] = Products.objects.all().count()
        context['col_all'] = Color.objects.all().count()
        context['banner'] = IndexBanner.objects.last()

        return context


def products_sale(request):
    return render(request, 'products/single-product-sale.html')


def product(request, product_name):
    context = {
        'product': Products.objects.get(name=product_name),
    }

    return render(request, 'products/single-product-variable.html', context)


@login_required
def basket_add(request, product_id):
    product = Products.objects.get(id=product_id)
    baskets = Basket.objects.filter(user=request.user, product=product)

    if not baskets.exists():
        Basket.objects.create(user=request.user, product=product, quantity=1)
    else:
        item = baskets.first()
        item.quantity += 1
        item.save()

    return HttpResponseRedirect(request.META['HTTP_REFERER'])


def basket_minus(request, basket_id):
    product = Products.objects.get(id=basket_id)
    baskets = Basket.objects.filter(user=request.user, product=product)

    item = baskets.first()
    if item.quantity != 0:
        item.quantity -= 1
        item.save()
    else:
        item.delete()

    return HttpResponseRedirect(request.META['HTTP_REFERER'])


def basket_remove(request, basket_id):
    basket = Basket.objects.get(id=basket_id)
    basket.delete()

    return HttpResponseRedirect(request.META['HTTP_REFERER'])


def wishlist_add(request, product_id):
    product = Products.objects.get(id=product_id)
    wishlist = Basket.objects.filter(user=request.user, product=product)

    if not wishlist.exists():
        Wishlist.objects.create(user=request.user, product=product)
    else:
        item = wishlist.first()
        item.quantity += 1
        item.save()

    return HttpResponseRedirect(request.META['HTTP_REFERER'])


def wishlist_remove(request, product_id):
    wish_product = Wishlist.objects.get(product_id=product_id)
    wish_product.delete()

    return HttpResponseRedirect(request.META['HTTP_REFERER'])

pronia-store/store/products/templates/products/cart.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}Pronia - Cart{% endblock %}

{% block main %}
  {% if not baskets %}
    <div class="breadcrumb-area breadcrumb-height" data-bg-image="{% static 'images/breadcrumb/bg/1-1-1919x388.jpg' %}">
      <div class="container h-100">
        <div class="row h-100">
          <div class="col-lg-12">
            <div class="breadcrumb-item">
              <h2 class="breadcrumb-heading">Cart is empty</h2>
              <ul>
                <li>
                  <a href="{% url 'products:index' %}">Go shopping</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  {% else %}
    <main class="main-content">
      <div class="breadcrumb-area breadcrumb-height"
        data-bg-image="{% static 'images/breadcrumb/bg/1-1-1919x388.jpg' %}">
        <div class="container h-100">
          <div class="row h-100">
            <div class="col-lg-12">
              <div class="breadcrumb-item">
                <h2 class="breadcrumb-heading">Cart Page</h2>
                <ul>
                  <li>
                    <a href="{% url 'index' %}">Home</a>
                  </li>
                  <li>Cart Page</li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="cart-area section-space-y-axis-100">
        <div class="container">
          <div class="row">
            <div class="col-12">
              <form action="javascript:void(0)">
                <div class="table-content table-responsive">
                  <table class="table">
                    <thead>
                    <tr>
                      <th class="product_remove">Remove</th>
                      <th class="product-thumbnail">Image</th>
                      <th class="cart-product-name">Product</th>
                      <th class="product-price">Unit Price</th>
                      <th class="product-quantity">Quantity</th>
                      <th class="product-subtotal">Total</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for basket in baskets %}
                      <tr>
                        <td class="product_remove">
                          <a href="{% url 'shop:basket_remove' basket.id %}">
                            <i class="pe-7s-close" data-tippy="Remove" data-tippy-inertia="true"
                              data-tippy-animation="shift-away" data-tippy-delay="50"
                              data-tippy-arrow="true" data-tippy-theme="sharpborder">
                            </i>
                          </a>
                        </td>
                        <td class="product-thumbnail">
                          <a href="{% url 'shop:product' basket.product.name %}">
                            <img src="{{ basket.product.image.url }}" alt="Cart Thumbnail">
                          </a>
                        </td>
                        <td class="product-name">
                          <a href="{% url 'shop:product' basket.product.name %}">{{ basket.product.name }}</a></td>
                        <td class="product-price"><span class="amount">${{ basket.product.price }}</span></td>
                        <td class="quantity">
                          <div class="input-group mb-3 inp-style">
                            <div class="input-group-prepend">
                              <a href="{% url 'shop:basket_minus' basket.product.id %}">
                                <button class="btn btn-outline-primary js-btn-minus" type="button">−</button>
                              </a>
                            </div>
                            <input
                              type="text"
                              class="form-control text-center"
                              value="{{ basket.quantity }}"
                              placeholder=""
                              aria-label="Example text with button addon"
                              aria-describedby="button-addon1"
                            >
                            <div class="input-group-append">
                              <a href="{% url 'shop:basket_add' basket.product.id %}">
                                <button class="btn btn-outline-primary js-btn-plus" type="button">+</button>
                              </a>
                            </div>
                          </div>
                        </td>
                        <td class="product-subtotal"><span class="amount">${{ basket.sum }}</span></td>
                      </tr>
                    {% endfor %}
                    </tbody>
                  </table>
                </div>
                <div class="row">
                  <div class="col-12">
                    <div class="coupon-all">
                      <div class="coupon">
                        <input id="coupon_code"
                          class="input-text"
                          name="coupon_code"
                          value=""
                          placeholder="Coupon code"
                          type="text">
                        <input class="button mt-xxs-30" name="apply_coupon" value="Apply coupon" type="submit">
                      </div>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-5 ml-auto">
                    <div class="cart-page-total">
                      <h2>Cart totals</h2>
                      <ul>
                        <li>Total Quantity <span>{{ baskets.total_quantity }}</span></li>
                        <li>Subtotal <span>${{ baskets.total_sum }}</span></li>
                        <li>Total <span>${{ baskets.total_sum }}</span></li>
                      </ul>
                      <a href="{% url 'user:checkout' %}">Proceed to checkout</a>
                    </div>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </main>
  {% endif %}
{% endblock %}

<script src="{% static 'js/quantity.js' %}"></script>

pronia-store/store/products/templates/products/shop.html
{% extends 'base/base.html' %}
{% load static cache %}

{% block title %}Pronia - Shop{% endblock %}

{% block main %}
  <main class="main-content">
    <div class="breadcrumb-area breadcrumb-height" data-bg-image="{% static 'images/breadcrumb/bg/1-1-1919x388.jpg' %}">
      <div class="container h-100">
        <div class="row h-100">
          <div class="col-lg-12">
            <div class="breadcrumb-item">
              <h2 class="breadcrumb-heading">Shop</h2>
              <ul>
                <li>
                  <a href="{% url 'index' %}">Home</a>
                </li>
                <li>Shop</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="shop-area section-space-y-axis-100">
      <div class="container">
        <div class="row">
          <div class="col-xl-3 col-lg-4 order-2 order-lg-1 pt-5 pt-lg-0">
            <div class="sidebar-area">
              <div class="widgets-searchbox">
                <form id="widgets-searchbox">
                  <input class="input-field" type="text" placeholder="Search">
                  <button class="widgets-searchbox-btn" type="submit">
                    <i class="fa fa-search"></i>
                  </button>
                </form>
              </div>

              <div class="widgets-area">
                <div class="widgets-item pt-0">
                  <h2 class="widgets-title mb-4">Categories</h2>
                  <ul class="widgets-category">
                    <li>
                      <a href="{% url 'shop:index' %}">
                        <i class="fa fa-chevron-right"></i> All <span>({{ prod_all }})</span>
                      </a>
                    </li>
                    {% cache 30 categories %}
                      {% for category in categories %}
                        <li>
                          <a href="{% url 'shop:categories' category.name %}">
                            <i class="fa fa-chevron-right"></i> {{ category.name }} <span>({{ category.products_set.count }})</span>
                          </a>
                        </li>
                      {% endfor %}
                    {% endcache %}
                  </ul>
                </div>
                <div class="widgets-item">
                  <h2 class="widgets-title mb-4">Color</h2>
                  <ul class="widgets-category widgets-color">
                    <li>
                      <a href="#">
                        <i class="fa fa-chevron-right"></i> All <span>({{ col_all }})</span>
                      </a>
                    </li>
                    {% for color in colors %}
                      <li>
                        <a href="#">
                          <i class="fa fa-chevron-right"></i> {{ color.name }} <span>()</span>
                        </a>
                      </li>
                    {% endfor %}
                  </ul>
                </div>
                <div class="widgets-item widgets-filter">
                  <h2 class="widgets-title mb-4">Price Filter</h2>
                  <div class="price-filter">
                    <input type="text"
                      class="pronia-range-slider"
                      name="pronia-range-slider"
                      value=""
                      data-type="double"
                      data-min="16"
                      data-from="16"
                      data-to="300"
                      data-max="350"
                      data-grid="false"/>
                  </div>
                </div>
                <div class="widgets-item">
                  <h2 class="widgets-title mb-4">Populer Tags</h2>
                  <ul class="widgets-tag">
                    {% for tag in tags %}
                      <li>
                        <a href="#">{{ tag.name }}</a>
                      </li>
                    {% endfor %}
                  </ul>
                </div>
              </div>

              <div class="banner-item widgets-banner img-hover-effect">
                <div class="banner-img">
                  <img src="{{ banner.image.url }}" alt="Banner Image">
                </div>
                <div class="banner-content text-position-center">
                  <span class="collection">New Collection</span>
                  <h3 class="title">Plant Port</h3>
                  <div class="button-wrap">
                    <a class="btn btn-custom-size sm-size btn-pronia-primary" href="#">Shop Now</a>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="col-xl-9 col-lg-8 order-1 order-lg-2">
            <div class="product-topbar">
              <ul>
                <li class="page-count">
                  <span>12</span> Product Found of <span>30</span>
                </li>

                <li class="product-view-wrap">
                  <ul class="nav" role="tablist">
                    <li class="grid-view" role="presentation">
                      <a class="active"
                        id="grid-view-tab"
                        data-bs-toggle="tab"
                        href="#grid-view"
                        role="tab"
                        aria-selected="true">
                        <i class="fa fa-th"></i>
                      </a>
                    </li>
                    <li class="list-view" role="presentation">
                      <a id="list-view-tab" data-bs-toggle="tab" href="#list-view" role="tab" aria-selected="true">
                        <i class="fa fa-th-list"></i>
                      </a>
                    </li>
                  </ul>
                </li>

                <li class="short">
                  <select class="nice-select">
                    <option value="1">Sort by Default</option>
                    <option value="2">Sort by Popularity</option>
                    <option value="3">Sort by Rated</option>
                    <option value="4">Sort by Latest</option>
                    <option value="5">Sort by High Price</option>
                    <option value="6">Sort by Low Price</option>
                  </select>
                </li>
              </ul>
            </div>

            <div class="tab-content">
              <div class="tab-pane fade show active" id="grid-view" role="tabpanel" aria-labelledby="grid-view-tab">
                <div class="product-grid-view row g-y-20">
                  {% cache 30 object_list %}
                    {% for product in object_list %}
                      <div class="col-md-4 col-sm-6">
                        <div class="product-item">
                          <div class="product-img">
                            <a href="{% url 'shop:product' product.name %}">
                              <img class="primary-img" src="{{ product.image.url }}" alt="Product Images">
                            </a>
                            <div class="product-add-action">
                              <ul>
                                <li>
                                  <a href="{% url 'user:wishlist' %}"
                                    data-tippy="Add to wishlist"
                                    data-tippy-inertia="true"
                                    data-tippy-animation="shift-away"
                                    data-tippy-delay="50"
                                    data-tippy-arrow="true"
                                    data-tippy-theme="sharpborder">
                                    <i class="pe-7s-like"></i>
                                  </a>
                                </li>
                                <li class="quuickview-btn" data-bs-toggle="modal" data-bs-target="#quickModal">
                                  <a href="#"
                                    data-tippy="Quickview"
                                    data-tippy-inertia="true"
                                    data-tippy-animation="shift-away"
                                    data-tippy-delay="50"
                                    data-tippy-arrow="true"
                                    data-tippy-theme="sharpborder">
                                    <i class="pe-7s-look"></i>
                                  </a>
                                </li>
                                <li>
                                  <a href="{% url 'shop:basket_add' product.id %}"
                                    data-tippy="Add to cart"
                                    data-tippy-inertia="true"
                                    data-tippy-animation="shift-away"
                                    data-tippy-delay="50"
                                    data-tippy-arrow="true"
                                    data-tippy-theme="sharpborder">
                                    <i class="pe-7s-cart"></i>
                                  </a>
                                </li>
                              </ul>
                            </div>
                          </div>
                          <div class="product-content">
                            <a class="product-name" href="{% url 'shop:product' product.name %}">{{ product.name }}</a>
                            <div class="price-box pb-1">
                              <span class="new-price">${{ product.price }}</span>
                            </div>
                            <div class="rating-box">
                              <ul>
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star"></i></li>
                              </ul>
                            </div>
                          </div>
                        </div>
                      </div>
                    {% endfor %}
                  {% endcache %}
                </div>
              </div>
            </div>

          {% if is_paginated %}
            <div class="pagination-area">
              <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                  <li class="page-item">
                    <a class="page-link"
                      href="
                        {% if page_obj.has_previous %}{% url 'shop:paginator' page_obj.previous_page_number %}{% else %}#{% endif %}"
                      aria-label="Previous">&laquo;</a>
                  </li>
                  {% for page in paginator.page_range %}
                    <li class="page-item"><a class="page-link" href="{% url 'shop:paginator' page %}">{{ page }}</a>
                    </li>
                  {% endfor %}
                  <li class="page-item">
                    <a class="page-link"
                      href="
                        {% if page_obj.has_next %}{% url 'shop:paginator' page_obj.next_page_number %}{% else %}#{% endif %}"
                      aria-label="Next">&raquo;</a>
                  </li>
                </ul>
              </nav>
            </div>
          {% endif %}
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}