megano/megano/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls', namespace='shop')),
    path('', include('users.urls', namespace='user')),
    path('', include('pages.urls', namespace='page')),
    path('', include('payments.urls', namespace='payment'))
]

if bool(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

megano/pages/urls.py
from django.urls import path

from .views import *

app_name = 'pages'

urlpatterns = [
    path('about/', about, name='about'),
    path('payment/<int:order_id>', payment, name='payment'),
    path('payment/<int:order_id>/good', payment_good, name='payment_good'),
    path('payment-someone/', payment_someone, name='payment-someone'),
    path('progress-payment/', progress_payment, name='progress-payment')
]

megano/products/urls.py
from django.urls import path

from . import views
from .views import *

app_name = 'products'

urlpatterns = [
    path('', index, name='index'),
    path('cart/', views.cart_view, name='cart'),
    path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<int:product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('basket/del/<int:product_id>/', basket_del, name='basket_del'),
    path('catalog/', shop, name='catalog'),
    path('catalog/category/<int:category_id>', shop, name='category'),
    path('catalog/tag/<int:tag_id>', shop, name='tag'),
    path('catalog/page/<page>/', shop, name='page'),
    path('sale/', sale, name='sale'),
    path('catalog/sale/page/<page>/', sale, name='sale-page'),
    path('product/<int:product_id>', product, name='product'),
    path('product/<int:product_id>/reviews/load/', load_more_reviews, name='load_reviews'),
    path('create/', OrderCreateView.as_view(), name='order_create'),
    path('order/create/step1/', OrderStepOneView.as_view(), name='order_step1'),
    path('order/create/step2/', OrderStepTwoView.as_view(), name='order_step2'),
    path('order/create/step3/', OrderStepThreeView.as_view(), name='order_step3'),
    path('order/create/confirm/', OrderConfirmView.as_view(), name='order_confirm'),
    path('order/success/', OrderSuccessView.as_view(), name='order_success'),
]

megano/users/urls.py
from django.urls import path

from .views import *

app_name = 'users'

urlpatterns = [
    path('account/', account, name='account'),
    path('history-order/', history_order, name='history-order'),
    path('order-detail/<int:order_id>', one_order, name='order-detail'),
    path('profile/', profile, name='profile'),
    path('register/', register, name='register'),
    path('login/',  my_login, name='login'),
    path('logout/', MyLogoutView.as_view(), name='logout'),
    path('change-password/', change_password, name='change_password'),
    path('change-profile-image/', change_profile_image, name='change_profile_image')
]

megano/base/models.py
from django.db import models

megano/base/views.py
from django.shortcuts import render

from products.models import Basket, Category


def header(request):
    baskets = Basket.objects.filter(user=request.user)

    total_sum = sum(basket.sum() for basket in baskets)

    context = {
        'total_sum': total_sum,
        'categories': Category.objects.all()
    }

    return render(request, 'base/header.html', context)

megano/base/templates/base/base.html
{% load static %}

<html lang="ru">

<head>
  <title>Megano</title>
  <meta name="description" content="Описание страницы">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">
  {% include 'base/css-and-fonts.html' %}
</head>

<body class="Site" id="site">
{% include 'base/header.html' %}

{% block content %}{% endblock %}

{% include 'base/footer.html' %}

{% block mixins %}{% endblock %}

{% include 'base/js-scripts.html' %}
</body>
</html>

megano/base/templates/base/css-and-fonts.html
{% load static %}

<link href="{% static 'frontend/favicon.ico' %}" rel="shortcut icon">
<link rel="preload" href="{% static 'frontend/assets/fonts/Roboto/Roboto-Regular.woff' %}" as="font">
<link rel="preload" href="{% static 'frontend/assets/fonts/Roboto/Roboto-Italic.woff' %}" as="font">
<link rel="preload" href="{% static 'frontend/assets/fonts/Roboto/Roboto-Bold.woff' %}" as="font">
<link rel="preload" href="{% static 'frontend/assets/fonts/Roboto/Roboto-Bold_Italic.woff' %}" as="font">
<link rel="preload" href="{% static 'frontend/assets/fonts/Roboto/Roboto-Light.woff' %}" as="font">
<link rel="preload" href="{% static 'frontend/assets/fonts/Roboto/Roboto-Light_Italic.woff' %}" as="font">
<link rel="stylesheet" href="{% static 'frontend/assets/css/fonts.css' %}">
<link rel="stylesheet" href="{% static 'frontend/assets/css/basic.css' %}">
<link rel="stylesheet" href="{% static 'frontend/assets/css/extra.css' %}">
<script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script src="{% static 'frontend/assets/plg/vue.global.js' %}"></script>
<script src="{% static 'frontend/assets/js/app.js' %}"></script>
<script src="{% static 'frontend/assets/plg/CountDown/countdown.js' %}"></script>

megano/base/templates/base/footer.html
{% load static %}

<footer class="Footer">
  <div class="wrap">
    <div class="row Footer-main">
      <div class="row-block">
        <a class="logo Footer-logo" href="{% url 'shop:index' %}">
          <img class="logo-image" src="{% static 'frontend/assets/img/logo_footer.png' %}" alt="logo_footer.png"/>
        </a>

        <p>
          Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincid unt ut laoreet
          dolore magna aliquam erat volutpat. Ut wisi enim ad
        </p>

        <ul class="menu menu_img menu_smallImg Footer-menuSoc">
          <li class="menu-item">
            <a class="menu-link" href="#">
              <img src="{% static 'frontend/assets/img/icons/socialFooter/fb.svg' %}" alt="fb.svg"/>
            </a>
          </li>

          <li class="menu-item">
            <a class="menu-link" href="#">
              <img src="{% static 'frontend/assets/img/icons/socialFooter/tw.svg' %}" alt="tw.svg"/>
            </a>
          </li>

          <li class="menu-item">
            <a class="menu-link" href="#">
              <img src="{% static 'frontend/assets/img/icons/socialFooter/in.svg' %}" alt="in.svg"/>
            </a>
          </li>

          <li class="menu-item">
            <a class="menu-link" href="#">
              <img src="{% static 'frontend/assets/img/icons/socialFooter/pt.svg' %}" alt="pt.svg"/>
            </a>
          </li>

          <li class="menu-item">
            <a class="menu-link" href="#">
              <img src="{% static 'frontend/assets/img/icons/socialFooter/mail.svg' %}" alt="mail.svg"/>
            </a>
          </li>
        </ul>
      </div>

      <div class="row-block">
        <strong class="Footer-title">Useful Links</strong>

        <ul class="menu menu_vt Footer-menu">
          <li class="menu-item">
            <a class="menu-link" href="{% url 'shop:cart' %}">My Cart</a>
          </li>

          <li class="menu-item">
            <a class="menu-link" href="{% url 'page:about' %}">Terms</a>
          </li>

          <li class="menu-item">
            <a class="menu-link" href="{% url 'page:about' %}">Conditions</a>
          </li>
        </ul>
      </div>

      <div class="row-block">
        <strong class="Footer-title">My Account</strong>

        <ul class="menu menu_vt Footer-menu">
          <li class="menu-item">
            <a class="menu-link" href="{% url 'shop:catalog' %}">Accessories</a>
          </li>

          <li class="menu-item">
            <a class="menu-link" href="{% url 'shop:catalog' %}">Bags</a>
          </li>

          <li class="menu-item">
            <a class="menu-link" href="{% url 'shop:catalog' %}">Cameras</a>
          </li>

          <li class="menu-item">
            <a class="menu-link" href="{% url 'shop:catalog' %}">Clothings</a>
          </li>

          <li class="menu-item">
            <a class="menu-link" href="{% url 'shop:catalog' %}">Electronics</a>
          </li>

          <li class="menu-item">
            <a class="menu-link" href="{% url 'shop:catalog' %}">Fashion</a>
          </li>
        </ul>
      </div>

      <div class="row-block">
        <strong class="Footer-title">Contacts</strong>

        <p>
          Phone: 8.800.200.600<br>
          Email: Support@ninzio.com<br>
          Skype: techno<br>
          Address: New York, north<br>
          Avenue 26/7<br>
          0057
        </p>
      </div>
    </div>
  </div>

  <div class="Footer-copy">
    <div class="wrap">
      <div class="row row_space">
        <div class="row-block">
          © Copyright&#32;
          <a href="{% url 'shop:index' %}">Megano Store.</a>
          &#32;All rights reserved.
        </div>

        <div class="row-block"><span>Accepted Payments</span>
          <div class="Footer-payments">
            <div>
              <img src="{% static 'frontend/assets/img/payments/visa.png' %}" alt="visa.png"/>
            </div>

            <div>
              <img src="{% static 'frontend/assets/img/payments/mastercard.png' %}" alt="mastercard.png"/>
            </div>

            <div>
              <img src="{% static 'frontend/assets/img/payments/paypal.png' %}" alt="paypal.png"/>
            </div>

            <div>
              <img src="{% static 'frontend/assets/img/payments/american.png' %}" alt="american.png"/>
            </div>

            <div>
              <img src="{% static 'frontend/assets/img/payments/electron.png' %}" alt="electron.png"/>
            </div>

            <div>
              <img src="{% static 'frontend/assets/img/payments/maestro.png' %}" alt="maestro.png"/>
            </div>

            <div>
              <img src="{% static 'frontend/assets/img/payments/delta.png' %}" alt="delta.png"/>
            </div>

            <div>
              <img src="{% static 'frontend/assets/img/payments/e.png' %}" alt="e.png"/>
            </div>

            <div>
              <img src="{% static 'frontend/assets/img/payments/dk.png' %}" alt="dk.png"/>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

megano/base/templates/base/header.html
{% load static %}

<header class="Header">
  <div class="ControlPanel">
    <div class="wrap">
      <div class="row ControlPanel-row">
        <div class="row-block">
          <div class="row ControlPanel-rowSplit">
            <div class="row-block">
              <a class="ControlPanel-title" href="{% url 'page:about' %}">
                Free delivery
              </a>
            </div>

            <div class="row-block hide_700"><span class="ControlPanel-title">Follow Us</span>
              <ul class="menu menu_img menu_smallImg ControlPanel-menu">
                <li class="menu-item">
                  <a class="menu-link" href="#">
                    <img src="{% static 'frontend/assets/img/icons/socialHeader/fb.svg' %}" alt="fb.svg"/>
                  </a>
                </li>

                <li class="menu-item">
                  <a class="menu-link" href="#">
                    <img src="{% static 'frontend/assets/img/icons/socialHeader/tw.svg' %}" alt="tw.svg"/>
                  </a>
                </li>

                <li class="menu-item">
                  <a class="menu-link" href="#">
                    <img src="{% static 'frontend/assets/img/icons/socialHeader/in.svg' %}" alt="in.svg"/>
                  </a>
                </li>

                <li class="menu-item">
                  <a class="menu-link" href="#">
                    <img src="{% static 'frontend/assets/img/icons/socialHeader/pt.svg' %}" alt="pt.svg"/>
                  </a>
                </li>

                <li class="menu-item">
                  <a class="menu-link" href="#">
                    <img src="{% static 'frontend/assets/img/icons/socialHeader/mail.svg' %}" alt="mail.svg"/>
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>

        <nav class="row-block">
          <div class="row ControlPanel-rowSplit">
            {% if user.is_authenticated %}
              <div class="row-block">
              <a class="ControlPanel-title" href="{% url 'users:profile' %}">{{ user.username }}</a>
              <a style="margin-left: 10px" class="ControlPanel-title" href="{% url 'users:logout' %}">Выйти</a>
            {% else %}
              <div class="row-block">
                <a class="ControlPanel-title" href="{% url 'users:login' %}">Login / Register</a>
              </div>
            {% endif %}
            </div>
          </div>
        </nav>
      </div>
    </div>
  </div>

  <div class="wrap">
    <div class="row Header-rowMain">
      <div class="row-block Header-logo">
        <a class="logo" href="{% url 'shop:index' %}">
          <img class="logo-image" src="{% static 'frontend/assets/img/logo.png' %}" alt="logo.png"/>
        </a>
      </div>

      <nav class="row-block row-block_right Header-menu">
        <div class="menuModal" id="navigate">
          <ul class="menu menu_main">
            <li class="menu-item">
              <a class="menu-link" href="{% url 'shop:index' %}">Home</a>
            </li>

            <li class="menu-item">
              <a class="menu-link" href="{% url 'shop:sale' %}">Sale</a>
            </li>

            <li class="menu-item">
              <span class="menu-label menu-label_success">Hot</span>
              <a class="menu-link" href="{% url 'shop:product' 1 %}">Product</a>
            </li>

            <li class="menu-item">
              <a class="menu-link" href="{% url 'shop:catalog' %}">Catalog</a>
            </li>
          </ul>
        </div>
      </nav>

      <div {% if not user.is_authenticated %} style="margin-right: 20px" {% endif %} class="row-block">
        <div class="CartBlock">
          <a class="CartBlock-block" href="{% url 'shop:cart' %}">
            <img class="CartBlock-img"
              src="{% static 'frontend/assets/img/icons/cart.svg' %}"
              alt="cart.svg"/>

            <span class="CartBlock-amount" v-text="basketCount.count"></span>
          </a>
          {% if user.is_authenticated %}
            <div class="CartBlock-block">
              <span class="CartBlock-price">{{ total_sum }}$</span>
            </div>
          {% endif %}
        </div>
      </div>

      <div class="row-block Header-trigger">
        <a class="menuTrigger" href="#navigate">
          <div class="menuTrigger-content">Показать навигацию</div>
          <span></span>
          <span></span>
          <span></span>
        </a>
      </div>
    </div>
  </div>

  <div class="Header-searchWrap">
    <div class="wrap">
      <div class="Header-categories">
        <div class="CategoriesButton">
          <div class="CategoriesButton-title">
            <div class="CategoriesButton-icon">
              <img src="{% static 'frontend/assets/img/icons/allDep.svg' %}" alt="allDep.svg"/>
            </div>

            <span class="CategoriesButton-text">All Departments</span>

            <div class="CategoriesButton-arrow"></div>
          </div>

          <div class="CategoriesButton-content">
            <div class="CategoriesButton-link" v-for="category in categories">
              <a href="{% url 'shop:catalog' %}">
                <span class="CategoriesButton-text">Категории товаров</span>
              </a>
              <a v-if="category.subcategories.length > 0"
                class="CategoriesButton-arrow"
                href="{% url 'shop:catalog' %}">
              </a>

              <div class="CategoriesButton-submenu">
                {% for category in categories %}
                  <div v-for="subcategory in category.subcategories">
                    <a class="CategoriesButton-link" href="{% url 'shop:category' category.pk %}">
                      <div class="CategoriesButton-icon">
                        <img :src="subcategory.image.src" :alt="subcategory.alt"/>
                      </div>
                      <span class="CategoriesButton-text">{{ category.name }}</span>
                    </a>
                  </div>
                {% endfor %}
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="Header-searchLink">
        <img src="{% static 'frontend/assets/img/icons/search.svg' %}" alt="search.svg"/>
      </div>

      <div class="Header-search">
        <div class="search">
          <form class="form form_search" @submit.prevent="search">
            <input class="search-input"
              id="query"
              name="query"
              type="text"
              v-model="searchText"
              placeholder="What are you looking for ..."/>
            <button class="search-button" type="submit" name="search" id="search">
              <img src="{% static 'frontend/assets/img/icons/search.svg' %}" alt="search.svg"/>Search
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
</header>

megano/base/templates/base/js-scripts.html
{% load static %}

<script src="{% static 'frontend/assets/js/app.js' %}"></script>
<script src="{% static 'frontend/assets/plg/jQuery/jquery-3.5.0.slim.min.js' %}"></script>
<script src="{% static 'frontend/assets/plg/form/jquery.form.js' %}"></script>
<script src="{% static 'frontend/assets/plg/form/jquery.maskedinput.min.js' %}"></script>
<script src="{% static 'frontend/assets/plg/range/ion.rangeSlider.min.js' %}"></script>
<script src="{% static 'frontend/assets/plg/Slider/slick.min.js' %}"></script>
<script src="{% static 'frontend/assets/js/scripts.js' %}"></script>
<script>
    var phoneInput = document.getElementById('id_phone');

    function formatPhone() {
        var phone = phoneInput.value;
        var digits = phone.replace(/\D/g, '');
        var formattedPhone = digits.replace(/(\d{1})(\d{3})(\d{3})(\d{2})(\d{2})/, '+7 ($2) $3-$4-$5');
        phoneInput.value = formattedPhone;
    }

    phoneInput.addEventListener('input', formatPhone);
</script>