amado-store/store/products/urls.py
from django.urls import path

from .views import *

app_name = 'products'

urlpatterns = [
    path('shop/product:<product_id>/', products, name='index'),
    path('shop/', shop, name='shop'),
    path('shop/sale/', sale, name='sale-shop'),
    path('shop/category/<category_id>/', shop, name='category'),
    path('shop/category/sale/<category_id>/', sale, name='sale-category'),
    path('page/<page>/', shop, name='page'),
    path('basket/add/', basket_add, name='basket_add'),
    path('basket/min/', basket_min, name='basket_min'),
    path('basket/del/', basket_del, name='basket_del'),
    path('set-language/', set_language, name='set_language'),
]

amado-store/store/store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from products.views import index, cart

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('cart/', cart, name='cart'),
    path('', include('products.urls', namespace='shop')),
    path('', include('products.urls', namespace='sale-shop')),
    path('users/', include('users.urls', namespace='users')),
]

if bool(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

amado-store/store/users/urls.py
from django.urls import path

from .views import authorization, registration, profile
from django.contrib.auth.views import LogoutView

app_name = 'users'

urlpatterns = [
    path('auth/', authorization, name='authorization'),
    path('register/', registration, name='registration'),
    path('profile/', profile, name='profile'),
    path('logout/', LogoutView.as_view(template_name="products/index.html"), name='logout'),
]

amado-store/store/products/models.py
from django.db import models

from users.models import User


class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Shop(models.Model):
    name = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=1, default=0)
    sale = models.IntegerField(blank=True, default=0)
    image = models.ImageField(upload_to='items', blank=True, null=True)
    main_image = models.ImageField(upload_to='main', blank=True)
    status_main = models.IntegerField(default=0, blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    order = models.PositiveIntegerField(default=0)

    class Meta:
        verbose_name_plural = 'Shop'

    def __str__(self):
        return self.name

    def prices(self):
        return {
            'old_price': self.price,
            'price': float(self.price * (100 - self.sale) / 100),
            'discount': self.sale
        }


class ShopImage(models.Model):
    product = models.ForeignKey(Shop, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='items', blank=True)

    class Meta:
        verbose_name_plural = 'ShopImages'

    def __str__(self):
        return f'Image for {self.product.name}'


class Brands(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'Brands'

    def __str__(self):
        return self.name


class Basket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
    price = models.PositiveIntegerField(default=0)
    sale = models.IntegerField(blank=True, default=0)
    quantity = models.PositiveIntegerField(default=0, blank=True, null=True)
    image = models.ImageField(upload_to='cart_image', blank=True)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Cart'

    def __str__(self):
        return f'Cart for {self.user.username} | Product {self.shop.name}'

    def sum(self):
        return self.quantity * (float(self.price * (100 - self.sale) / 100))


class BasketItem(models.Model):
    item = models.CharField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'Items'

    def __str__(self):
        return self.item

amado-store/store/products/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator

from .models import Category, Brands, Shop, Basket, BasketItem
from store import settings


def index(request, user_id=None):
    context = {
        'index': Shop.objects.exclude(status_main=0),
    }

    if request.user:
        baskets = Basket.objects.filter(user=user_id)
        context.update(dict(baskets=baskets))

    return render(request, 'products/index.html', context)


@login_required
def cart(request):
    baskets = Basket.objects.filter(user=request.user)

    total_sum = sum(basket.sum() for basket in baskets)

    context = {
        'baskets': baskets,
        'basket_item': BasketItem.objects.all(),
        'total_sum': total_sum,
    }

    if not baskets:
        return render(request, 'products/blank_cart.html')
    else:
        return render(request, 'products/cart.html', context)


@login_required
def basket_add(request):
    current_page = request.META.get('HTTP_REFERER')
    shops = Shop.objects.get(id=request.POST['product_id'])
    price = shops.price
    sale = shops.sale
    image = shops.image
    baskets = Basket.objects.filter(
        user=request.user,
        price=price,
        image=image,
        shop=shops.id,
        sale=sale
    )

    if not baskets.exists():
        Basket.objects.create(
            user=request.user,
            shop=shops,
            price=price,
            sale=sale,
            image=image,
            quantity=1
        )
        return HttpResponseRedirect(current_page)
    else:
        basket = baskets.first()
        basket.quantity += 1
        basket.save()
        return HttpResponseRedirect(current_page)


@login_required
def basket_min(request):
    current_page = request.META.get('HTTP_REFERER')
    shops = Shop.objects.get(id=request.POST['product_id'])
    price = shops.price
    sale = shops.sale
    image = shops.image
    baskets = Basket.objects.filter(
        user=request.user,
        price=price,
        sale=sale,
        image=image,
        shop=shops.id
    )

    if not baskets.exists():
        Basket.objects.create(
            user=request.user,
            shop=shops,
            price=price,
            sale=sale,
            image=image,
            quantity=1
        )
        return HttpResponseRedirect(current_page)
    else:
        basket = baskets.first()
        if basket.quantity != 0:
            basket.quantity -= 1
            basket.save()

        return HttpResponseRedirect(current_page)


@login_required
def basket_del(request):
    basket = Basket.objects.get(id=request.POST['id'])
    basket.delete()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def products(request, product_id=None, user_id=None):
    context = {
        'categories': Category.objects.all(),
        'products': Shop.objects.filter(pk=product_id, status_main=0),
        'similars': Shop.objects.order_by('-order', '?').filter(status_main=0)
    }
    if request.user:
        baskets = Basket.objects.filter(user=user_id)
        context.update(dict(baskets=baskets))

    return render(request, 'products/products.html', context)


def shop(request, category_id=None, page=1, user_id=None):
    context = {
        'categories': Category.objects.all(),
        'brands': Brands.objects.all(),
        'shop': Shop.objects.exclude(status_main=1),
        'products_count': Shop.objects.exclude(status_main=1),
    }

    if request.user:
        baskets = Basket.objects.filter(user=user_id)
        context.update(dict(baskets=baskets))

    if category_id:
        shops = Shop.objects.order_by('-order').filter(category_id=category_id, status_main=0)
    else:
        shops = Shop.objects.order_by('-order').filter(status_main=0)

    shops_paginator = Paginator(shops, 4).page(page)
    context.update({'shop': shops_paginator})

    return render(request, 'products/shop.html', context)


def sale(request, category_id=None, page=1, user_id=None):
    context = {
        'categories': Category.objects.all(),
        'brands': Brands.objects.all(),
        'shop_sale': Shop.objects.filter(status_main=0).exclude(sale=0),
        'products_count': Shop.objects.exclude(sale=0).filter(status_main=0),
    }

    print(context)

    if request.user:
        baskets = Basket.objects.filter(user=user_id)
        context.update(dict(baskets=baskets))

    if category_id:
        shops_sale = Shop.objects\
            .order_by('-order')\
            .filter(category_id=category_id, status_main=0)\
            .exclude(sale=0)
    else:
        shops_sale = Shop.objects\
            .order_by('-order')\
            .filter(status_main=0)\
            .exclude(sale=0)

    shops_sale_paginator = Paginator(shops_sale, 4).page(page)
    context.update({'shop_sale': shops_sale_paginator})

    return render(request, 'products/sale-shop.html', context)


@login_required
def set_language(request):
    lang = request.GET.get('l', 'en')
    request.session[settings.LANGUAGE_SESSION_KEY] = lang
    response = HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))
    response.set_cookie(settings.LANGUAGE_COOKIE_NAME, lang)

    return response

amado-store/store/products/templates/products/base.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="ru">

{% if user.id %}
  {% get_available_languages as LANGUAGES %}
  {% for lang in LANGUAGES %}
    {% if LANGUAGE_CODE == lang.0 %}
      {{ lang.1 }} ({{ lang.0 }})
    {% else %}
      <a href="{% url 'products:set_language' %}?l={{ lang.0 }}">{{ lang.1 }} ({{ lang.0 }})</a>
    {% endif %}
  {% endfor %}
{% endif %}

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="icon" href="{% static 'img/core-img/favicon.ico' %}">
  <link rel="stylesheet" href="{% static 'css/core-style.css' %}">
  <title>{% block title %} {% endblock %}</title>
</head>

<body>
<div class="main-content-wrapper d-flex clearfix">
  {% include 'products/header.html' %}
  {% block content %}{% endblock %}
</div>

{% include 'products/footer.html' %}
{% include 'products/js_style.html' %}

</body>
</html>

amado-store/store/products/templates/products/blank_cart.html
{% extends 'products/base.html' %}
{% load static %}
{% load i18n %}

{% block title %}
  {% trans 'Amado - Furniture Ecommerce Template | Cart' %}
{% endblock %}

{% block content %}
  <div class="cart-table-area section-padding-100">
    <div class="container-fluid">
      <div class="row">
        <div class="col-12 col-lg-8">
          <div class="cart-title mt-50">
            <h2>{% trans 'Shopping Cart' %}</h2>
          </div>
          &nbsp;
          <h1>{% trans 'Basket is empty' %}</h1>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

amado-store/store/products/templates/products/cart.html
{% extends 'products/base.html' %}
{% load static %}
{% load i18n %}

{% block title %}
  {% trans 'Amado - Furniture Ecommerce Template | Cart' %}
{% endblock %}

{% if cart %}
  {% block content %}
    <div class="cart-table-area section-padding-100">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12 col-lg-8">
            <div class="cart-title mt-50">
              <h2>{% trans 'Shopping Cart' %}</h2>
            </div>

            <div class="cart-table clearfix">
              <table class="table table-responsive">
                <thead>
                <tr>
                  <th></th>
                  {% for item in basket_item %}
                    <th>{{ item.item }}</th>
                  {% endfor %}
                </tr>
                </thead>

                <tbody>
                {% for basket in baskets %}
                  <tr>
                    <td class="cart_product_img">
                      <a href="{% url 'products:index' basket.shop.pk %}">
                        <img src="{{ basket.shop.image.url }}" alt="">
                      </a>
                    </td>

                    <td class="cart_product_desc">
                      <a class="fz-16"
                        href="{% url 'products:index' basket.shop.pk %}">{{ basket.shop.name }}</a>
                    </td>

                    <td class="price">
                      <span>${{ basket.sum }}</span>
                    </td>

                    <td class="qty">
                      <div class="qty-btn d-flex">
                        <p>Qty: {{ basket.quantity }}</p>
                      </div>
                      &nbsp;&nbsp;&nbsp;

                      <form action="{% url 'products:basket_del' %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="id" value="{{ basket.id }}">
                        <div class="col-6 mb-3">
                          <button
                            type="submit"
                            data-toggle="tooltip"
                            data-placement="left"
                            title="{% trans 'Remove from cart' %}"
                          >
                            <img src="{% static 'img/core-img/delete.png' %}" alt="">
                          </button>
                        </div>
                      </form>

                      <form action="{% url 'products:basket_add' %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="product_id" value="{{ basket.shop.id }}">
                        <div class="col-6 mb-3">
                          <button
                            type="submit"
                            data-toggle="tooltip"
                            data-placement="left"
                            title="{% trans 'Enlarge' %}"
                          >
                            <img src="{% static 'img/core-img/dob_plus.png' %}" alt="">
                          </button>
                        </div>
                      </form>

                      <form action="{% url 'products:basket_min' %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="product_id" value="{{ basket.shop.id }}">
                        <div class="col-6 mb-3">
                          <button
                            type="submit"
                            data-toggle="tooltip"
                            data-placement="left"
                            title="{% trans 'Reduce' %}"
                          >
                            <img src="{% static 'img/core-img/minus.png' %}" alt="">
                          </button>
                        </div>
                      </form>
                    </td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
            </div>
          </div>

          <div class="col-12 col-lg-4">
            <div class="cart-summary">
              <h5>{% trans 'Cart Total' %}</h5>
              <ul class="summary-table">
                <li>
                  <span>{% trans 'subtotal:' %}</span>
                  <span>${{ total_sum }}</span>
                </li>
                <li>
                  <span>{% trans 'delivery:' %}</span>
                  <span>{% trans 'Free' %}</span>
                </li>
                <li>
                  <span>{% trans 'total:' %}</span>
                  <span>${{ total_sum }}</span>
                </li>
              </ul>

              <div class="cart-btn mt-100">
                <a href="{% url 'cart' %}" class="btn amado-btn w-100">{% trans 'Checkout' %}</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  {% endblock %}
{% endif %}

amado-store/store/products/templates/products/footer.html
{% load static %}
{% load i18n %}

<section class="newsletter-area section-padding-100-0">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-12 col-lg-6 col-xl-7">
        <div class="newsletter-text mb-100">
          <h2>{% trans 'Subscribe for a ' %}<span>{% trans '25% Discount' %}</span></h2>
          <p>Nulla ac convallis lorem, eget euismod nisl. Donec in libero sit amet mi vulputate
            consectetur. Donec auctor interdum purus, ac finibus massa bibendum nec.</p>
        </div>
      </div>

      <div class="col-12 col-lg-6 col-xl-5">
        <div class="newsletter-form mb-100">
          <form action="#" method="post">
            <label>
              <input type="email" name="email" class="nl-email" placeholder="{% trans 'Your E-mail' %}">
            </label>
            <input type="submit" value="{% trans 'Subscribe' %}">
          </form>
        </div>
      </div>
    </div>
  </div>
</section>

<footer class="footer_area clearfix">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-12 col-lg-8">
        <div class="single_widget_area">
          <div class="footer_menu">
            <nav class="navbar navbar-expand-lg justify-content-end">
              <button
                class="navbar-toggler"
                type="button"
                data-toggle="collapse"
                data-target="#footerNavContent"
                aria-controls="footerNavContent"
                aria-expanded="false"
                aria-label="Toggle navigation"
              >
                <i class="fa fa-bars"></i>
              </button>
              <div class="collapse navbar-collapse" id="footerNavContent">
                <ul class="navbar-nav ml-auto">
                  <li class="nav-item active">
                    <a class="nav-link" href="{% url 'index' %}">{% trans 'Home' %}</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'products:shop' %}">{% trans 'Shop' %}</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'cart' %}">{% trans 'Cart' %}</a>
                  </li>
                </ul>
              </div>
            </nav>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

amado-store/store/products/templates/products/header.html
{% load static %}
{% load i18n %}

<header class="header-area clearfix">
  <div class="nav-close">
    <i class="fa fa-close" aria-hidden="true"></i>
  </div>

  <div class="logo">
    <a href="{% url 'index' %}"><img src="{% static 'img/core-img/logo.png' %}" alt=""></a>
  </div>

  <nav class="amado-nav">
    <ul>
      <li>
        <a href="{% url 'index' %}">{% trans 'Home' %}</a>
      </li>

      <li>
        <a href="{% url 'products:shop' %}">{% trans 'Shop' %}</a>
      </li>

      {% if user.id %}
        <li>
          <a href="{% url 'cart' %}">{% trans 'Cart' %}</a>
        </li>
      {% else %}
        <li>
          <a href="{% url 'users:authorization' %}">{% trans 'Cart' %}</a>
        </li>
      {% endif %}
    </ul>
  </nav>

  <div class="amado-btn-group">
    <a href="{% url 'products:sale-shop' %}" class="btn amado-btn mb-15">{% trans 'Discount' %}</a>
  </div>

  {% if user.id %}
    <div class="cart-fav-search mb-100">
      <a href="{% url 'users:profile' %}" class="search-nav">
        <img
          src="{% static 'img/core-img/profile.png' %}"
          alt=""
        >
        {% trans 'Profile' %}
      </a>

      <a href="{% url 'cart' %}" class="cart-nav">
        <img
          src="{% static 'img/core-img/cart.png' %}"
          alt=""
        >
        {% trans 'Cart' %}
      </a>

      <a href="{% url 'users:logout' %}" class="search-nav">
        <img
          src="{% static 'img/core-img/exit.png' %}"
          alt=""
        >
        {% trans 'Exit' %}
      </a>
    </div>
  {% else %}
    <div class="cart-fav-search mb-100">
      <a href="{% url 'users:authorization' %}" class="search-nav">
        <img src="{% static 'img/core-img/authorization.png' %}" alt="">
        {% trans 'Authorization' %}
      </a>
    </div>
  {% endif %}

  <div class="social-info d-flex justify-content-between">
    <a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
    <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
    <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
    <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
  </div>
</header>

amado-store/store/products/templates/products/index.html
{% extends 'products/base.html' %}
{% load static %}
{% load i18n %}

{% block title %}
  {% trans 'Amado - Furniture Ecommerce Template | Home' %}
{% endblock %}

{% block content %}
  <div class="products-catagories-area clearfix">
    <div class="amado-pro-catagory clearfix">
      {% for item in index %}
        <div class="single-products-catagory clearfix">
          <a href="{% url 'products:shop' %}">
            <img src="{{ item.main_image.url }}" alt="">

            <div class="hover-content">
              <div class="line"></div>
              <p>{% trans 'From ' %} ${{ item.price }}</p>
              <h4>{{ item.name }}</h4>
            </div>
          </a>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

amado-store/store/products/templates/products/sale-shop.html
{% extends 'products/base.html' %}
{% load static %}
{% load i18n %}

{% block title %}
  {% trans 'Amado - Furniture Ecommerce Template | Shop' %}
{% endblock %}

{% block content %}
  <div class="shop_sidebar_area">
    <div class="widget catagory mb-50">
      <h6 class="widget-title mb-30">{% trans 'Categories' %}</h6>

      <div class="catagories-menu">
        <ul>
          {% for category in categories %}
            <li>
              <a href="{% url 'sale-shop:sale-category' category.pk %}">{{ category.name }}</a>
            </li>
          {% endfor %}
          <li>
            <a href="{% url 'products:sale-shop' %}">Reset filter</a>
          </li>
        </ul>
      </div>
    </div>
  </div>

  <div class="amado_product_area section-padding-100">
    <div class="container-fluid">
      <div class="row">
        <div class="col-12">
          <div class="product-topbar d-xl-flex align-items-end justify-content-between">
            <div class="total-products">
              <p>{% trans 'Showing 1-4 of' %} {{ products_count.count }}</p>
            </div>

            <div class="product-sorting d-flex">
              <div class="sort-by-date d-flex align-items-center mr-15">
                <p>{% trans 'Sort by' %}</p>
                <label for="sortBydate"></label>
                <select name="select" id="sortBydate">
                  <option value="value">{% trans 'Date' %}</option>
                  <option value="value">{% trans 'Newest' %}</option>
                  <option value="value">{% trans 'Popular' %}</option>
                </select>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        {% for item in shop_sale %}
          <div class="col-12 col-sm-6 col-md-12 col-xl-6">
            <div class="single-product-wrapper">
              <div class="product-img">
                <a
                  href="{% url 'products:index' item.pk %}"
                  class="d-block w-100"
                >
                  <img src="{{ item.image.url }}" alt="">
                </a>
              </div>

              <div class="product-description d-flex align-items-center justify-content-between">
                <div class="product-meta-data">
                  <div class="d-in-bl">
                    <p class="product-price fl-l">${{ item.prices.price }}</p>
                    <p class="product-old-price fl-l">${{ item.prices.old_price }}</p>
                  </div>

                  <a href="{% url 'products:index' item.pk %}">
                    <h6>{{ item.name }}</h6>
                  </a>
                </div>

                <div class="ratings-cart text-right">
                  <div class="ratings">
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star" aria-hidden="true"></i>
                  </div>

                  {% if user.id %}
                    <div class="cart">
                      <form action="{% url 'products:basket_add' %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="product_id" value="{{ item.id }}">
                        <button
                          type="submit"
                          data-toggle="tooltip"
                          data-placement="left"
                          title="Add to Cart"
                        >
                          <img src="{% static 'img/core-img/cart.png' %}" alt="" method="post">
                        </button>
                      </form>
                    </div>
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>

      <div class="row">
        <div class="col-12">
          <nav aria-label="navigation">
            <ul class="pagination justify-content-end mt-50">
              {% for page in shop_sale.paginator.page_range %}
                <li class="page-item active">
                  <a class="page-link" href="{% url 'sale-shop:page' page %}">{{ page }}</a>
                </li>
              {% endfor %}
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

amado-store/store/products/templates/products/shop.html
{% extends 'products/base.html' %}
{% load static %}
{% load i18n %}

{% block title %}
  {% trans 'Amado - Furniture Ecommerce Template | Shop' %}
{% endblock %}

{% block content %}
  <div class="shop_sidebar_area">
    <div class="widget catagory mb-50">
      <h6 class="widget-title mb-30">{% trans 'Categories' %}</h6>
      <div class="catagories-menu">
        <ul>
          {% for category in categories %}
            <li><a href="{% url 'shop:category' category.pk %}">{{ category.name }}</a></li>
          {% endfor %}
          <li><a href="{% url 'products:shop'%}">Reset filter</a></li>
        </ul>
      </div>
    </div>
  </div>

  <div class="amado_product_area section-padding-100">
    <div class="container-fluid">
      <div class="row">
        <div class="col-12">
          <div class="product-topbar d-xl-flex align-items-end justify-content-between">
            <div class="total-products">
              <p>{% trans 'Showing 1-4 of' %} {{ products_count.count }}</p>
            </div>

            <div class="product-sorting d-flex">
              <div class="sort-by-date d-flex align-items-center mr-15">
                <p>{% trans 'Sort by' %}</p>
                <label for="sortBydate"></label><select name="select" id="sortBydate">
                <option value="value">{% trans 'Date' %}</option>
                <option value="value">{% trans 'Newest' %}</option>
                <option value="value">{% trans 'Popular' %}</option>
              </select>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        {% for product in shop %}
          <div class="col-12 col-sm-6 col-md-12 col-xl-6">
            <div class="single-product-wrapper">
              <div class="product-img">
                <a
                  href="{% url 'products:index' product.pk %}"
                  class="d-block w-100"
                >
                  <img src="{{ product.image.url }}" alt="">
                </a>
              </div>

              <div class="product-description d-flex align-items-center justify-content-between">
                <div class="product-meta-data">
                  <div class="d-in-bl">
                    <p class="product-price fl-l">${{ product.prices.price }}</p>
                    {% if product.prices.discount > 0 %}
                      <p class="product-old-price fl-l">${{ product.prices.old_price }}</p>
                    {% endif %}
                  </div>

                  <a href="{% url 'products:index' product.pk %}">
                    <h6>{{ product.name }}</h6>
                  </a>
                </div>

                <div class="ratings-cart text-right">
                  <div class="ratings">
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star" aria-hidden="true"></i>
                  </div>

                  {% if user.id %}
                    <div class="cart">
                      <form action="{% url 'products:basket_add' %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="product_id" value="{{ product.id }}">
                        <button
                          type="submit"
                          data-toggle="tooltip"
                          data-placement="left"
                          title="Add to Cart"
                        >
                          <img src="{% static 'img/core-img/cart.png' %}" alt="" method="post">
                        </button>
                      </form>
                    </div>
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>

      <div class="row">
        <div class="col-12">
          <nav aria-label="navigation">
            <ul class="pagination justify-content-end mt-50">
              {% for page in shop.paginator.page_range %}
                <li class="page-item active">
                  <a
                    class="page-link"
                    href="{% url 'shop:page' page %}"
                  >
                    {{ page }}
                  </a>
                </li>
              {% endfor %}
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </div>
{% endblock %}